### ISSUE TITLE
the app has good sisign BUT...

### ISSUE THREAD

**Issue by inKdahood** [OffRange/PasswordManager#12]
When i try to put a 256bit passcode (~60 character) or more the app accept it but i cant open the app with it and the app hard crash so there is no way to put a "real" password 
The app say nothing just crash 
Its sad for a secure app

**Comment by inKdahood** [comment]
Hello, glad to help.
I use the last update we can find in release on github actually i just discover the app for say all.
I use a password generator who use ascii 32-255 (32 is for space consider as a chatacter and is included)
I can use him for 32-126 to.
With ascii a character is 7bit so for make a 256bit password  we need minimum ~34 to ~70 characters in fonction of the combination of char you use for your password and in 32-126 and 32-255 the app accept the code for creating the file save and open after creating but if i enter a password for save it and close the app when i restart the app and want type my password to acces all my password in the vault the app crash and the vault is close for eternity and i need to uninstall reinstall to clear the app vault save file 
(Its sad bcs i want a 1024bit password to be honest (157-170char in ascii))
I dont tried with fingerprint access if the fingerprint can open it or if it crash like typing access but fingerprint is not really safe in reality so i dont want to use this feature 
Here is my use of the app : 
First i have a password manager for local password its keepass the best for real strong pass and full local passcode compatible with pc and android i use this app for open my local sensitive data on android and pc its the best way for me but keepass is not necessary the best in practice on android and i dont need a 1024 bit password on my nintendo account for exemple and its annoying to have enter 160 on my switch console so for these account i continue to need tape them password, there is where i want this app i want a passcode manager who can handle all my 13-20 char password on android but i need to protect it with a big code to access to it so aro

**Comment by inKdahood** [comment]
Hello, glad to help.
I use the last update we can find in release on github actually i just discover the app this week for say all.
I use a password generator who use ascii 32-255 (32 is for space consider as a chatacter and is included in password generated)
I can use him in ascii 32-126 to.
With ascii a character is 7bit so for make a 256bit password we need minimum ~34 to ~70 characters in fonction of the combination of char you use for your password. In 32-126 and 32-255 the app accept the code for creating the save vault file and open it after creating but if i enter something for save it in the app and close the app, when i restart the app and want type my password to acces all my file in the vault the app crash and the vault cant be open in 0 case i succed to reopen it after the creating opening and i need to uninstall reinstall to clear the app vault save file and restart all from 0
With typing method with copy paste and with auto fill from keepass thats all the same issue
(Its sad bcs i want a 1024bit password to be honest (157-170char in ascii))

I dont tried with fingerprint access if the fingerprint can open it or if it crash like typing access but fingerprint is not really safe in reality so i dont want to use this feature.

Here is my use of the app if that can help you to see some trouble :
First i have a password manager for local password its keepass the best for real strong pass and full local passcode compatible with pc and android i use this app for open my local sensitive data on android and pc with some 1024bit password its the best way for me but keepass is not necessary the best in practice on android and i dont need a 1024 bit password on my nintendo account for exemple and its annoying to need enter 160 char on my switch console just for playing mario kart xD 
so for these account i continue to need tape them password, there is where i want your app i want a passcode manager who can handle all my 13-20 char password on it and more easy to access on android like keepass but i need to protect it with a big code to access to it so around 60-160 char i want to open the vault one time and keep it open for the day close when i go sleep on keepass android changr database when i need local pass or online or this or this... its to long and annoying so a app just for it is cool hope that story help you to see why i want that long password  for the app 

Again i precise if my english not good enough for understand something dont hesitate to tell me

**Comment by inKdahood** [comment]
Sorry i closed the issue accidently

**Comment by OffRange** [comment]
Thank you for reporting this issue!

I'm pleased to inform you that I have successfully resolved the problem and pushed the necessary fixes. I will be incorporating this fix into the upcoming release, which is scheduled for next week/weekend. Alongside the fix, the new version will also include a few other small features.

Once again, thank you for bringing this issue to my attention, and your patience is highly appreciated.

I would appreciate it if you could give the new version a try once it's available. Your feedback would be valuable in ensuring the stability and effectiveness of the improvements.

**Comment by OffRange** [comment]
Check out the latest [release candidate](https://github.com/OffRange/PasswordManager/releases)
