### ISSUE TITLE
Backup Feature 

### ISSUE THREAD

**Issue by J4k3v3** [OffRange/PasswordManager#29]
**Feature Request**

**Description:**
Add a backup feature for all cards and passwords

**Use Case:**
I think, backup feature - it's so good and useful feature for all of us. And I wanna ask developers - can you add this thing?

**Proposed Solution:**
My idea - use simple .txt file with configs data encrypted in .aes format, the password of which will be either manually set by the user or  use the password of KeyGo app. Every user will get the opportunity to save this file to any directory or cloud drive. You can use any formats or style of this feature, this is just my humble proposal :)

**Comment by OffRange** [comment]
KeyGo already supports the export and import of passwords, as implemented in the latest release [`v1.2.0`](https://github.com/OffRange/KeyGo/releases/tag/v1.2.0). Regarding your feature request, it appears to overlap with a previously submitted request (#25) on GitHub.

However, implementing a backup feature using a simple .txt file poses security concerns. Therefore, I won't be pursuing this approach. Additionally, KeyGo doesn't have many config files/settings that users can change. Therefore, the effort of implementing support for config data wouldn't be justified.

Instead, I recommend utilizing the already supported kdbx file format for securely backing up your data. Users already have the option to change the file extension format (kdbx), but internally KeyGo will still export to this format, ensuring robust encryption and protection of your sensitive information.

Additionally, please note that support for credit cards is planned for future releases, as stated in #25. I appreciate your patience and understanding as I work on enhancing KeyGo's features. Thank you for your valuable suggestion and continued support.
